service: alexa-skills-kit-color-expert-go

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ask-go:
    handler: bin/main
    memorySize: 256
    timeout: 10
    events:
      - alexaSkill